### ISSUE TITLE
Make Compatible not doing anything?

### ISSUE THREAD

**Issue by Mark2Mark** [simoncozens/GlyphsScripts#7]
https://github.com/simoncozens/GlyphsScripts/blob/fdb6a601a2bc227e1296ad2759e01dda3103e58b/Make%20Compatible.py#L15

Is it supposed to make paths compatible, that have different counts of segments? If so, the zip() function might not be the right thing there, or am i wrong? zip will always ignore the item from a list that is to many compared to the other list. But I think I am wrong and missing something. Cannot follow the code properly, as I don’t understand how it is supposed to work. At least it doesn’t do anything, when you have a 4-on-curve-circle in one master and the same, but with an extra ocp in the other master.

**Comment by simoncozens** [comment]
> Is it supposed to make paths compatible, that have different counts of segments? 

Ah, no it's not. (I'm not sure how you would do that reliably.) It should, however, do something sensible in that case rather than blow up.

**Comment by Mark2Mark** [comment]
What’s it supposed to do then? Just curious :)

**Comment by simoncozens** [comment]
It's supposed to fix the construction when the number of on-curves is the same - i.e. when segments in some masters are curves but others masters have lines (which need to become curves). It's suprisingly common when VF-ing sources.

**Comment by Mark2Mark** [comment]
ah, I see. Makes sense. Thanks for that!
